### ISSUE TITLE
[Bug] - No se puede borrar el texto

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#100]
`Impacto:` Medio
`Plataforma`: PC
`Descripción:` El juego no te permite borrar el texto que has escrito para tu nombre.
`Pasos para reproducirlo:` Escribo un texto en pantalla normal, lo borro, pantalla completa, escribo un texto muy largo y ya no me deja borrar.

**Comment by MrPotato027** [comment]
Arreglado
