### ISSUE TITLE
[usabilidad] - Falta feedback de la llave

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#101]
`Impacto:` Medio
`Entorno:` Pc y Móvil
`Descripción:` Cuando coges la llave no sabes si has desbloqueado la puerta o tienes que hacer algo más, lo intuyes, pero no lo sabes, estaría bien añadir algún tipo de feedback visual para que cuando cojas la llave la puerta se abra o que tuviera un candado que desaparece cuando la coges.

**Comment by aitoorgrc** [comment]
Arreglado.
