### ISSUE TITLE
[Bug] - Varios menús en pantalla

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#103]
`Impacto:` Medio
`Entorno:` PC
`Descripción:` Pueden aparecer varios menús a la vez en pantalla.
`Pasos para reproducirlo:` Abres el menú, seleccionas opciones y después pulsas escape, y entonces te aparece debajo del menú opciones el menú normal, y desde ahí puedes pulsar el botón salir del juego, sin necesidad de cerrar el menú de opciones

**Comment by MrPotato027** [comment]
Arreglado.
