### ISSUE TITLE
[Bug] - No hay guardado de los ajustes entre menú principal y juego

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#104]
`Impacto:` Medio
`Plataforma`: PC
`Descripción:` Si cambias el volumen en la pantalla inicial y después pasas a los ajustes dentro del gameplay los valores de sonido no se guardan.
`Pasos para reproducirlo:` Cambias los ajustes de volumen desde el menú principal, y al entrar en el juego vuelves a entrar en el menú de opciones y puedes observar que el volumen no se ha actualizado.

**Comment by MrPotato027** [comment]
ERROR
