### ISSUE TITLE
[Conexión] - Cuando se desconecta un jugador se cierra el juego

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#105]
`Impacto:` Alto
`Entorno:` PC y Móvil
`Descripción:` Cuando un jugador se desconecta en mitad de una partida el otro jugador sale automáticamente a la pantalla de inicio, sin ningún mensaje ni aviso de que es lo que ha sucedido.
`Pasos para reproducirlo:` Inicia el juego y conéctate a una sala, empezar la partida, y que algún jugador cierre la pestaña del juego.

**Comment by aitoorgrc** [comment]
Arreglado.
