### ISSUE TITLE
[Bug] - Se puede acumular salto

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#106]
`Impacto:` Medio
`Plataforma`: PC
`Descripción:` Si te pones bajo un objeto que esté cerca de ti pero que te permita saltar un poco y empiezas a pulsar repetidamente el salto y mientras te mueves hacia el borde, puedes hacer un salto muy alto que te permite llegar a grandes alturas. 
`Pasos para reproducirlo:` Solo ha sucedido una vez y no hemos sido capaces de reproducirlo.

**Comment by MrPotato027** [comment]
No hemos sido capaces de replicarlo.
