### ISSUE TITLE
[Conexión] - No se puede volver a jugar

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#107]
`Impacto:` Critico
`Entorno:` PC y Móvil
`Descripción:` Si hay una desconexión y la partida se cierra, no se puede volver a jugar partida ni crearla sin reiniciar el juego.
`Pasos para reproducirlo:` Crea una partida, desconéctate e intenta volver a jugar.

**Comment by MrPotato027** [comment]
ERROR
