### ISSUE TITLE
[Conexión] - Desconexión de jugadores

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#108]
`Impacto:` Critico
`Entorno:` PC y Móvil
`Descripción:` Puedes dejar al jugador 2 sin poder jugar ni salir del menú de espera de selección de nivel.
`Pasos para reproducirlo:` Al entrar en partida y dar a jugar, el jugador 2 debe esperar sin poder ir hacia atrás a que el jugador 1 elija un nivel. Pero puede darse el caso de que el jugador 1 decida ir hacia atrás sin que esta información llegue al jugador 2 dejándolo bloqueado en la espera de nivel sin poder hacer nada.

**Comment by MrPotato027** [comment]
arreglado
