### ISSUE TITLE
[Bug] - Puedes acabar boca abajo

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#110]
`Impacto:` Crítico
`Entorno:` PC y Móvil
`Descripción:` Si te pones a saltar con gravedad invertida cerca de donde están los otros triggers de invertir gravedad puedes conseguir acabar boca abajo; el problema es que al estar boca abajo no puedes saltar y tampoco te permite cambiar de gravedad con los triggers laterales.
`Pasos para conseguirlo:` saltar con gravedad invertida cerca de donde están los otros triggers de invertir gravedad.
![image](https://user-images.githubusercontent.com/91122387/143489008-7a08b480-fa93-4984-a9d9-dc4525510fb6.png)

**Comment by MrPotato027** [comment]
Mejorado.
