### ISSUE TITLE
[Bug] - Quedarse volando

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#111]
`Impacto:` Medio
`Plataforma`: PC
`Descripción:` Puedes chocarte de una forma especifica contra una caja y conseguir quedarte volando al lado de esa caja, si sueltas el botón de moverte caes, pero puedes quedarte ahí enganchado.
`Pasos para reproducirlo:` Debes saltar con la intención de golpearte contra una caja en el costado y mantener la tecla de la dirección en la que vas.

**Comment by MrPotato027** [comment]
Arreglado.
