### ISSUE TITLE
[Bug] - Volar con los osos

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#112]
`Impacto:` Medio
`Plataforma`: PC y móvil
`Descripción:` Los osos pueden conseguir volar juntos de forma indefinida
`Pasos para reproducirlo:` Si los dos osos se ponen uno frente a otro y saltan juntos se puede hacer que ambos consideren al otro como una plataforma constantemente, dejando a los jugadores ascender infinitamente si tienen buena coordinación.

**Comment by MrPotato027** [comment]
Arreglado.
