### ISSUE TITLE
[Bug] - Atravesar obstáculos

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#114]
`Impacto:` Medio
`Plataforma`: PC
`Descripción:` Las plataformas que desaparecen te permiten atravesarlas a partir de cierta altura si justo se vuelven a activar.
`Pasos para reproducirlo:` Activar una plataforma justo cuando un oso esta atravesándola.

**Comment by MrPotato027** [comment]
No es un bug.
