### ISSUE TITLE
[Grafico] - Gráficamente gran parte de los assets del escenario no son visibles

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#115]
`Impacto:` Crítico
`Entorno:` Móvil
`Descripción:` Al abrir el juego e iniciar partida, gran parte de elementos del escenario se ven en negro, de modo que no se distinguen las plataformas del fondo, siendo imposible avanzar.
![image](https://user-images.githubusercontent.com/91122387/143479157-de08552a-e018-44e3-9d61-271338054edf.png)

**Comment by MrPotato027** [comment]
No lo hemos podido reproducir.
