### ISSUE TITLE
[Bug] - El oso se queda moviéndose en una dirección

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#117]
`Impacto:` Alto
`Entorno:` PC
`Descripción:` el jugador estaba moviéndose hacia la izquierda sin permitirme cambiar de dirección.
`Pasos para conseguirlo:` No hemos sido capaces de repetirlo, y solo ha pasado una vez.

**Comment by MrPotato027** [comment]
No hemos sido capaces de replicarlo.
