### ISSUE TITLE
[Bug] - El nivel 9 se pasa solo

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#118]
`Impacto:` Medio
`Plataforma`: PC
`Descripción:` El nivel 9 te permite pasar el nivel entero sin necesidad de moverte, atravesando cajas, paredes y cualquier objeto.
`Pasos para reproducirlo:` El jugador se encuentra entre 2 objetos que no le permiten moverse a izquierda o derecha; por lo tanto los objetos que vienen de frente moviéndose en dirección contraria chocan contigo, pero no te empujan ya que tienes un objeto detras que te lo impide, por lo tanto si te quedas quieto atraviesas todos los objetos que te encuentres.

**Comment by aitoorgrc** [comment]
Arreglado.
