### ISSUE TITLE
[Bug] - Error en las cajas en el nivel 3

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#120]
`Impacto:` Medio
`Plataforma`: PC y móvil
`Descripción:` Al tirar la caja de arriba encima de la de abajo para poder llevarlas a la derecha y superar el nivel, muchas veces se colocan de formas extrañas y se van descolocando según las vas empujando hacia derecha o izquierda.
`Pasos para reproducirlo:` Tirar una caja encima de otra o juntarlas cuando ambas están el suelo.
![image](https://user-images.githubusercontent.com/91122387/143490129-c396b35d-1aaf-4173-b51a-9bc252f3e1cd.png)

**Comment by MrPotato027** [comment]
Arreglado.
