### ISSUE TITLE
Fallo en persistencia de niveles superados

### ISSUE THREAD

**Issue by julio-guillen** [pandagamerstudio/ZooEscape#128]
Impacto
Medio

Entorno: PC y Móvil
Los niveles superados no dependen del usuario sino del navegador

Pasos para replicarlo
Crea una nueva partida con otro nombre de usuario

![image](https://user-images.githubusercontent.com/25005788/145567580-88ba62f0-b2bc-401e-94d9-6839d0898ce2.png)

**Comment by MrPotato027** [comment]
Esto es una decisión consensuada.
