### ISSUE TITLE
Listado de partidas muestra partidas finalizadas

### ISSUE THREAD

**Issue by julio-guillen** [pandagamerstudio/ZooEscape#130]
**Impacto**
Medio

**Entorno: PC y Móvil**
Al hacer pruebas de crear y eliminar partidas

**Pasos para replicarlo**
No replicable

![image](https://user-images.githubusercontent.com/25005788/145568572-e89df8e4-0ddf-4267-a78a-c461ffd8a22d.png)

**Comment by MrPotato027** [comment]
Arreglado.
