### ISSUE TITLE
Partida nueva encuentra jugador fantasma

### ISSUE THREAD

**Issue by julio-guillen** [pandagamerstudio/ZooEscape#131]
**Impacto**
Medio

**Entorno: PC y Móvil**
Haciendo pruebas de crear y destruir partidas. Puede que se deba al uso de un mismo navegador.

**Pasos para replicarlo**
No replicado

![image](https://user-images.githubusercontent.com/25005788/145568867-e6b54859-0d6d-4a72-aa86-ccf5de600728.png)

**Comment by julio-guillen** [comment]
Una extensión al bug.

Puedo agregar a un jugador nuevo, pero entonces no se visualizan correctamente los osos elegidos por cada uno, somo si por un lado el sistema entiende que hay dos jugadores, pero por otro, el visualizador de la interfaz no.

![image](https://user-images.githubusercontent.com/25005788/145569084-7fb4f7e7-92bc-4f7b-8180-9a0f0caa9062.png)

Al final, el sistema no puede iniciar la partida ya que parece que no es consciente de ue hay dos jugadores:

![image](https://user-images.githubusercontent.com/25005788/145569187-6829f3d8-d5dc-4d0b-9bdf-4e87c93d8ff3.png)

**Comment by MrPotato027** [comment]
Arreglado.
