### ISSUE TITLE
Número negativo en las cajas

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#54]
`Impacto:` Bajo.
`Plataforma o entorno:` ordenador y dispositivos móviles.
`Descripción:` al situarse dos jugadores cerca de una caja que solo requiera de un jugador, la caja pasará a mostrar -1.
`Pasos para reproducirlo:` Esto se puede reproducir en el nivel 3, cuando dos jugadores se acercan a una caja

![image](https://user-images.githubusercontent.com/93185865/142925634-da6dc0e0-47a4-47d7-a835-8da39a1c35c4.png)

**Comment by MrPotato027** [comment]
Arreglado
