### ISSUE TITLE
Caja atascada entre pared y plataforma

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#56]
`Impacto`: Alto
`Plataforma o entorno:` Ordenador y dispositivo móvil
`Descripción:` En uno de los niveles (6) se da la situación en el que uno de los jugadores tiene que tirar una caja al vacío por un lugar muy estrecho y se queda atascada, por tanto, no se puede subir a la plataforma central y pasar el nivel
`Pasos para reproducirlo:` En el nivel 6, un jugador tiene que dirigirse a la parte derecha de la pantalla, subir a la plataforma y tirar la caja que se encuentra arriba.

![image](https://user-images.githubusercontent.com/93185865/142927813-3d2f13d4-b2b5-4431-b575-38d330b954c6.png)

**Comment by MrPotato027** [comment]
Arreglado
