### ISSUE TITLE
Problemas con las cajas (Superposición, clipping)

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#57]
`Impacto:` Medio
`Plataforma o entorno:` Ordenador y dispositivos móviles
`Descripción:` Para poder superar uno de los niveles (nivel 3), uno de los jugadores tiene que tirar una caja al vacío para que aterrice sobre otra y así formar una caja más alta para poder llegar a una plataforma. Al intentar colocar una encima de la otra, se presenta un error en el que se superponen, desaparece o se descoloca una de las cajas. La pantalla de uno de los jugadores muestra una cosa distinta a la del otro.
Para pasar el nivel hay que hacer uso del cuerpo del otro personaje. De esta forma se salta doble y se puede llegar arriba
`Pasos para reproducirlo:` En el nivel 3, cuando hay que poner una caja encima de otra.

### VIEW 1
![6e992355a94b9b6c60bf381e4f91a6df](https://user-images.githubusercontent.com/93185865/142930380-6595179b-b490-4e6c-bc38-9e035843d9e3.gif)

### VIEW 2
![image](https://user-images.githubusercontent.com/93185865/142929908-b29767d5-5b43-4a21-abd7-413003423447.png)

**Comment by MrPotato027** [comment]
Arreglado
