### ISSUE TITLE
El nivel de la gravedad presenta problemas

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#58]
`Impacto:` Alto.
`Plataforma o entorno:` Ordenador y dispositivos móviles.
`Descripción:` El jugador no puede continuar el nivel debido a que se queda pegado al techo.
`Pasos para reproducirlo:` Cuando se cambia la gravedad, ya sea a paredes o al techo, el jugador se puede quedar bloqueado y tiene que reiniciar el nivel.

![0fe93ee0c48a052fec5393cabdb39225](https://user-images.githubusercontent.com/93185865/142930140-b3d9ac7b-3506-4d58-b26c-8ad5067758b9.gif)
![image](https://user-images.githubusercontent.com/93185865/142930236-4f5d2c20-9fb9-47ae-b05a-8bd12a4bbe2d.png)

**Comment by MrPotato027** [comment]
Mejorado.
