### ISSUE TITLE
Campo de texto del nombre no desaparece 

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#61]
`Impacto:` Bajo
`Plataforma o entorno:` Dispositivo móvil (en navegador Chrome)
`Descripción:` Cuando se rellena el campo del nombre en el dispositivo móvil, si no se presiona el botón de "Enter" del teclado del móvil, el campo de texto se superpone en la pantalla.
`Pasos para reproducirlo:` Introducir el nombre en el campo de texto del móvil y presionar el botón de "Retroceso" en él.

![image](https://user-images.githubusercontent.com/93185865/142933032-f1608648-178a-45bd-afc1-81c4fdc5bc45.png)
![image](https://user-images.githubusercontent.com/93185865/142933061-24aeafc7-c760-4531-8e10-563c95db837f.png)

**Comment by MrPotato027** [comment]
No sabemos el origen del error.
