### ISSUE TITLE
Input del móvil detectado como presionado o deshabilitado

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#62]
`Impacto:` Medio .
`Plataforma o entorno:` Dispositivo móvil.
`Descripción:` Cuando el input de movimiento se deja de presionar, se sigue detectando que se está presionando. También ocurre que en ocasiones, se presiona el input y no reacciona al movimiento (se soluciona presionando varias veces el botón de saltar y ya se puede volver a mover).
`Pasos para reproducirlo:` El error ocurre ocasionalmente, pero no se han determinado los pasos concretos para reproducirlo. Ha ocurrido durante una sesión de juego.

**Comment by MrPotato027** [comment]
No encontrado.
