### ISSUE TITLE
Pérdida de progresión de los niveles

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#63]
`Impacto:` Alto
`Plataforma o entorno:` Ordenador y dispositivo móvil.
`Descripción:` Una vez se ha superado el juego, el mismo te sugiere que puedes volver a revisitar los niveles. Si eliges un nivel y pierdes tus vidas, tus puzles o partidas guardadas se pierden.
`Pasos para reproducirlo:` Morir tras revisitar un nivel ya superado.

**Comment by MrPotato027** [comment]
Arreglado
