### ISSUE TITLE
Las salas no aparecen entre navegadores distintos

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#64]
`Impacto:` Crítico
`Plataforma o entorno:` Ordenador y dispositivo móvil.
`Descripción:` Las salas no figuran como creadas entre navegadores de distinto tipo (Chrome y Firefox).
`Pasos para reproducirlo:` Crear una sala en Chrome y buscar salas en Firefox y viceversa.

De Chrome a Chrome:

https://user-images.githubusercontent.com/93185865/143083012-95a8a461-efb8-41b9-83e8-569cddef772e.mp4

De Chrome a Firefox:

https://user-images.githubusercontent.com/93185865/143083285-c746adc6-d0fe-43fb-93ef-8705350f5c46.mp4

**Comment by MrPotato027** [comment]
ERROR
