### ISSUE TITLE
Menor potencia de salto al pegarse a la pared

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#67]
`Impacto:` Medio.
`Plataforma o entorno:` Ordenador y Dispositivo móvil.
`Descripción:` En ocasiones, si el jugador se pega mucho a una pared (con el input de movimiento pulsado) y salta, el salto no alcanza el alto necesario para atravesar el obstáculo.
`Pasos para reproducirlo:` Ir caminando hacia una pared y, sin soltar el input de movimiento, saltar. Ocurre ocasionalmente

https://user-images.githubusercontent.com/93185865/143084472-598284d1-efd2-4606-98c6-39d390f7ad88.mp4

.

**Comment by MrPotato027** [comment]
Arreglado.
