### ISSUE TITLE
Las salas no aparecen entre chrome de ordenador y de móvil

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#68]
`Impacto:` Crítico
`Plataforma o entorno:` Ordenador y Dispositivo móvil (Chrome-Chrome).
`Descripción:` Si en Chrome de ordenador se crea una sala, esta no aparece en la pantalla de rooms del Chrome de dispositivo móvil.
`Pasos para reproducirlo:` Crear una sala en Chrome de ordenador e intentar buscarla en Chrome de móviles y viceversa.

**Comment by MrPotato027** [comment]
FALSO
