### ISSUE TITLE
Ajuste de sfx y música se sale del slider al llegar al mínimo.

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#69]
`Impacto:` Bajo.
`Plataforma o entorno:` Ordenador y Dispositivo móvil.
`Descripción:` El punto de ajuste de volumen de música y SFX se sale del slider.
`Pasos para reproducirlo:` Bajar el volumen al mínimo en la pantalla de opciones.

![image](https://user-images.githubusercontent.com/93185865/143085306-54da70fb-b422-40a2-a2d4-86f43688f30b.png)

**Comment by MrPotato027** [comment]
Arreglado
