### ISSUE TITLE
Restringir el número de caracteres permitidos en campo de nombre de usuario y de sala.

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#70]
`Impacto:` Bajo.
`Plataforma o entorno:` Ordenador y Dispositivo móvil.
`Descripción:` Si se ponen muchos caracteres de nombre tanto para crear sala como para introducir nombre de usuario, se extienden.
`Pasos para reproducirlo:` Introducir muchos caracteres en el espacio de nombre, tanto de usuario como de room.

![image](https://user-images.githubusercontent.com/93185865/143085650-ba175500-b00b-44d4-ad92-367ceadbc7af.png)

**Comment by MrPotato027** [comment]
Arreglado
