### ISSUE TITLE
Número de jugadores a 0 en la lobby

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#71]
`Impacto:` Medio.
`Plataforma o entorno:` Ordenador y Dispositivo móvil.
`Descripción:` En la lobby de salas, puede darse la situación de encontrarse una lobby con 0/0 jugadores.
`Pasos para reproducirlo:` Crear una sala, meterse a jugar (un jugador solo), salirse de la partida y refrescar las lobbys con el segundo jugador.

![image](https://user-images.githubusercontent.com/93185865/143085916-58883b25-fd56-4fca-9bff-8363b21bad8d.png)

**Comment by MrPotato027** [comment]
Problemas de photon, no podemos hacer nada.
