### ISSUE TITLE
Sliders de opciones pequeños en el móvil.

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#72]
`Impacto:` Bajo
`Plataforma o entorno:` Dispositivo móvil.
`Descripción:` Los sliders de la pantalla de opciones se ven demasiado pequeños en un dispositivo móvil.
`Pasos para reproducirlo:` Abrir la pestaña de opciones en un dispositivo móvil.

![image](https://user-images.githubusercontent.com/93185865/143086244-da350c31-00c4-42a9-bfe0-558461d1b3f3.png)

**Comment by MrPotato027** [comment]
Arreglado
