### ISSUE TITLE
No se alcanza bien una plataforma del nivel 6

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#73]
`Impacto:` Medio.
`Plataforma o entorno:` Ordenador y dispositivo móvil.
`Descripción:` Es complicado alcanzar una de las plataformas del nivel 6 dado que el salto se queda muy justo.
`Pasos para reproducirlo:` Dirigirse en el nivel 6 hacia la plataforma móvil de la derecha del mapa e intentar, una vez llegado a su tope, saltar a la plataforma que tiene la caja. El jugador se queda corto en numerosas ocasiones

**Comment by MrPotato027** [comment]
Arreglado
