### ISSUE TITLE
Errores visuales en dispositivo móvil.

### ISSUE THREAD

**Issue by TheNidesRA** [pandagamerstudio/ZooEscape#75]
`Impacto:` Crítico (en el dispositivo afectado).
`Plataforma o entorno:` Dispositivo móvil.
`Descripción:` El error ocurre en el dispositivo Samsung Galaxy S10 e y jugando con otra persona (si se juega en solitario, no ocurre). No se visualizan correctamente los gráficos del nivel, poniéndose un fondo oscuro y sin dejar ver las plataformas y el entorno de juego.
`Pasos para reproducirlo:` Conectarse junto a otro jugador desde el dispositivo Samsung Galaxy S10 e.

![image](https://user-images.githubusercontent.com/93185865/143087520-9cceeba8-1749-46bd-9d39-557b4f9a744b.png)

**Comment by MrPotato027** [comment]
No lo hemos podido reproducir.
