### ISSUE TITLE
[Conexion] - Jugadores iguales

### ISSUE THREAD

**Issue by strikealex** [pandagamerstudio/ZooEscape#76]
`Impacto:` bajo
`Plataforma o entorno:` PC y móvil.
`Descripción:` Ambos jugadores pueden elegir el mismo oso, por lo tanto al entrar en el juego es difícil distinguir quien es quien. 
`Pasos para reproducirlo:` escoger ambos el mismo oso en la sala de partida.

**Comment by MrPotato027** [comment]
Arreglado
