### ISSUE TITLE
[Conexion] - Eliminación de salas

### ISSUE THREAD

**Issue by strikealex** [pandagamerstudio/ZooEscape#78]
`Impacto:` Medio
`Plataforma o entorno:` PC y móvil.
`Descripción:` Al salir de una sala todos los jugadores, esta sala sigue apareciendo en el menú de selección de sala.
`Pasos para reproducirlo:` Creas una sala y jugáis una partida, si los jugadores salen al menú principal y entrar al menú de selección de sala aparece la sala en la que estaban jugando, si no, se pulsa el botón refresh y ya debería aparecer.

**Comment by MrPotato027** [comment]
PHOTON
