### ISSUE TITLE
[Conexion] - No aparecen las salas para jugar

### ISSUE THREAD

**Issue by SaYoTiTo** [pandagamerstudio/ZooEscape#79]
`Impacto:` Crítico
`Entorno:` PC y Móvil
`Descripción:` Con muchas salas abiertas ocurren errores, no aparecen todas las salas a la hora de buscar partida y no parece haber ningún motivo de selección de las salas que si aparecen.
`Pasos para reproducirlo:`

**Comment by MrPotato027** [comment]
PHOTON
