### ISSUE TITLE
[Conexion] - Error de StackOverflow

### ISSUE THREAD

**Issue by SaYoTiTo** [pandagamerstudio/ZooEscape#80]
`Impacto:` Crítico
`Entorno:` PC
`Descripción:` Si te mantienes mucho rato en una partida sin terminarla, el servidor te cerrara el juego o en otro caso te dará un error de StackOverflow.
`Pasos para reproducirlo:` Desconocido

**Comment by MrPotato027** [comment]
No hemos conseguido repetirlo.
