### ISSUE TITLE
[Conexion] - Errores de sincronización de posición de los personajes

### ISSUE THREAD

**Issue by SaYoTiTo** [pandagamerstudio/ZooEscape#81]
`Impacto:` Crítico
`Entorno:` PC
`Descripción:` La posición de los jugadores a veces no es la misma en ambas pantallas, pudiendo darse el caso de que en la pantalla del segundo jugador ambos estén en la puerta, terminando el nivel, pero en la pantalla del primero el segundo jugador no esté sobre la puerta, de modo que al no poder ya moverse, sea imposible para el primer jugador finalizar el nivel y pasar al siguiente.
`Pasos para reproducirlo:` Es un error grave que no sabemos reproducir y que solo ha ocurrido una vez

**Comment by MrPotato027** [comment]
Photon.
