### ISSUE TITLE
[Conexion] - Errores de sincronización de posición de plataformas móviles

### ISSUE THREAD

**Issue by strikealex** [pandagamerstudio/ZooEscape#82]
`Impacto:` Medio
`Plataforma o entorno:` PC.
`Descripción:` Los elementos moviles del juego no estan sincronizados bien, y a veces se puede ver a un jugador volando en el aire mientras la plataforma esta en otro lado.
`Pasos para reproducirlo:` Hay que llegar al nivel 6 y quedarte debajo de la plataforma de la derecha, y cuando esta baje, empezar a saltar, de esta forma a veces pasa este bug.

**Comment by MrPotato027** [comment]
Photon.
