### ISSUE TITLE
[Conexion] - Olvida tu nombre

### ISSUE THREAD

**Issue by strikealex** [pandagamerstudio/ZooEscape#83]
`Impacto:` Bajo
`Plataforma o entorno:` PC y Móvil
`Descripción:` Si inicias una partida y después sales de ella, en la caja para tu nombre no aparece nada.
`Pasos para reproducirlo:` Entras en una sala y después sales de esa partida, le das a jugar en el menú principal, y ahí se verá que no tienes un nombre.

**Comment by MrPotato027** [comment]
Arreglado.
