### ISSUE TITLE
[Conexión] - Entrar en sala sin nombre

### ISSUE THREAD

**Issue by strikealex** [pandagamerstudio/ZooEscape#84]
`Impacto:` Medio
`Plataforma o entorno:` PC
`Descripción:` El juego te deja iniciar una partida sin tener que poner un nombre, aunque cuando entras tienes el nombre que tenias antes guardado. Sucede lo mismo con el nombre de las salas.
`Pasos para reproducirlo:` Primero tienes que crear una sala, salir de ella y después darle a play, así podrás unirte a una sala o crear una propia sin poner ningún nombre.

**Comment by MrPotato027** [comment]
Arreglado.
