### ISSUE TITLE
[Bug] - Posibilidad de realizar salto doble sobre la puerta

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#85]
`Impacto:` Bajo
`Plataforma`: PC
`Descripción:` Puedes hacer un doble salto justo encima de la puerta de salida.
`Pasos para reproducirlo:` Si saltas repetidamente encima de la puerta para pasar la siguiente nivel te permite saltar 2 veces sin tocar el suelo.

**Comment by MrPotato027** [comment]
Arreglado.
