### ISSUE TITLE
[Bug] - Escalar paredes

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#86]
`Impacto:` Bajo
`Plataforma`: PC y móvil
`Descripción:` Se puede escalar por las paredes si saltas cerca de ellas, miras hacia el otro lado, vuelves a mirar a la pared y saltas.
`Pasos para reproducirlo:` Saltar junto a una pared, girarse al lado contrario y volver al de la pared rápidamente y volver a saltar.

**Comment by MrPotato027** [comment]
Arreglado.
