### ISSUE TITLE
[Bug] - Marcha atrás

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#87]
`Impacto:` Bajo
`Plataforma`: PC y móvil
`Descripción:` Al activar una palanca y cambiar de tamaño el personaje siempre se pone mirando a la derecha haciendo que en ocasiones si estabas yendo hacia la izquierda y das a la palanca el oso siga su camino pero de espaldas.
`Pasos para reproducirlo:` Activar una palanca mientras se anda hacia la izquierda.

**Comment by MrPotato027** [comment]
Arreglado
