### ISSUE TITLE
[Diseño] - El nombre no se ve bien

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#88]
`Impacto:` Medio

`Entorno:` PC

`Descripción:` Si introduces un texto muy largo en la caja de texto del nombre o de la sala, lo borras y escribes un texto normal, la caja de texto deja de estar centrada y aparece a al izquierda del todo a penas viéndose.

**Comment by MrPotato027** [comment]
Arreglado.
