### ISSUE TITLE
[Diseño] - No hay control de longitud de texto

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#89]
`Impacto:` Medio
`Entorno:` PC
`Descripción:` No hay limite de longitud de texto para el nombre ni para la sala; así que puedes introducir tantos caracteres como quieras.
`Pasos para reproducirlo:` Introduces un texto muy largo en cualquiera de los cuadros de texto; nosotros hemos introducido 5 párrafos de lorem ipsum.
![image](https://user-images.githubusercontent.com/91122387/143484905-23b9a907-2a38-403c-a6a7-8b38fba2b46b.png)

**Comment by MrPotato027** [comment]
Arreglado.
