### ISSUE TITLE
[Bug] - No deja introducir nombre

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#90]
`Impacto:` Medio
`Plataforma`: PC
`Descripción:` El juego solo te permite introducir una letra como nombre en pantalla completa si antes has puesto algo en pantalla pequeña.
`Pasos para reproducirlo:` Si introduces una letra en pantalla pequeña y después pones pantalla completa e intentas cambiar tu nombre, solo te deja introducir una letra, puedes cambiar esta letra tantas veces como quieras, simplemente es que solo se guarda la ultima letra que escribas.

**Comment by MrPotato027** [comment]
Arreglado
