### ISSUE TITLE
[Diseño] - Disposición de niveles poco intuitiva

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#91]
`Impacto:` Medio
`Entorno:` PC y Móvil
`Descripción:` En la selección de niveles, éstos no están colocados de derecha a izquierda y de arriba a abajo, sino de arriba a abajo y de derecha a izquierda; es poco intuitivo ya que la mayoría de juegos con niveles suelen tenerlo de derecha a izquierda y de arriba a abajo, no a la inversa.
`Pasos para reproducirlo:` Abrir el juego, crear una sala y empezar la partida, se puede observar en la pantalla de selección de nivel.

**Comment by MrPotato027** [comment]
Arreglado.
