### ISSUE TITLE
[Diseño] - Nivel 6 Problemas de diseño

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#92]
`Impacto:` Medio
`Entorno:` PC y Móvil
`Descripción:` Puedes subir al ascensor sin necesidad de la caja, haciendo que sea posible pasarse el nivel sin tener que resolver el puzle.
`Pasos para reproducirlo:` Para poder subir al ascensor sin la caja debes hacer un pequeños bug en el que saltas en el lateral de la plataforma.

**Comment by MrPotato027** [comment]
Arreglado
