### ISSUE TITLE
[Diseño] - Nivel 7 Fuera del escenario

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#93]
`Impacto:` Critico
`Entorno:` PC y Móvil
`Descripción:` Puedes salir fuera del escenario andando
`Pasos para reproducirlo:` Debes ser el jugador que aparece arriba, andas hacia el final del mapa por la izquierda y saltas encima de la caja, te acercas hasta el limite y saltas, da igual si eres grande o pequeño, si saltas puedes pasar por encima del limite y salirte fuera del mapa.

**Comment by MrPotato027** [comment]
Arreglado.
