### ISSUE TITLE
[Bug] - Errores de introducción de texto

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#94]
`Impacto:` Medio
`Plataforma`: PC
`Descripción:` Al introducir un nombre de sala o jugador con la pantalla completa se bloquean la opción de moverse por el texto con las flechas de dirección y borrar el texto.
`Pasos para reproducirlo:` Poner el juego en pantalla completa e introducir un nombre de sala o de usuario.

**Comment by MrPotato027** [comment]
Arreglado
