### ISSUE TITLE
[Diseño] - Se permite el modo un jugador

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#95]
`Impacto:` Crítico
`Entorno:` PC y Móvil
`Descripción:` Si estoy jugando solo no puedo avanzar de nivel porque me obliga a tener que llegar los dos osos a la puerta; sin embargo te permite iniciar la partida con solo un jugador, dando a entender que se puede jugar solo.
`Pasos para reproducirlo:` Inicia el juego, crea una sala y dale a start.

**Comment by MrPotato027** [comment]
Arreglado.
