### ISSUE TITLE
[Bug] - Nombre al revés

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#96]
`Impacto:` Medio
`Plataforma`: PC
`Descripción:` Inicias el juego en pantalla completa y escribes tu nombre, se escribe al revés, de derecha a izquierda.
`Pasos para reproducirlo:` Poner el juego en pantalla completa e introducir un nombre de sala o de usuario.

**Comment by MrPotato027** [comment]
Arreglado
