### ISSUE TITLE
[Usabilidad] - Cajas de texto en móvil

### ISSUE THREAD

**Issue by salmorejogames** [pandagamerstudio/ZooEscape#98]
`Impacto:` Bajo
`Entorno:` Móvil
`Descripción:` En dispositivos móviles a la hora de introducir los nombres de sala o jugador se despliega una innecesaria caja de introducción de texto delante del menú real del juego, además el texto de la caja tiene una fuente bastante grande y si no le das a aceptar se queda la caja de texto encima del resto de la interfaz, pero te permite moverte por los menús.

**Comment by MrPotato027** [comment]
No podemos cambiar ni el tamaño de la fuente del texto.
